<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ConfigLens.Infrastructure/ConfigLens.Infrastructure.csproj" />
  </ItemGroup>

</Project>
